[project]
name = "mircat-seg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "dynamic-network-architectures>=0.3.1",
    "monai==1.3.1",
    "torch==2.3.1",
]

[project.scripts]
mircat-seg = "mircat_seg:mircat_seg"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
